### ISSUE TITLE
empty package in npm

### ISSUE THREAD

**Issue by tonyalaribe** [philmander/mobx-preact#2]
The module on npm is empty. no javascript file defining anything

**Comment by nightwolfz** [comment]
Wow that's weird. I published the files but I didn't even have time to test if they work properly.

@tonyalaribe Let me know if anything weird happens

**Comment by denizdogan** [comment]
I don't do TypeScript, so I have no idea where the problem lies, but here's what happens to me... 

    import { Provider, connect } from 'mobx-preact';
    console.log(Provider); // undefined

    import MobxPreact from 'mobx-preact';
    console.log(MobxPreact.Provider); // function ...

I'm not sure what's going on?

**Comment by nightwolfz** [comment]
@denizdogan Can you check the latest version? I'm travelling at the moment so it's kind of hard to fix things on my phone :)

**Comment by mweststrate** [comment]
Probably a there is only a default export but no normal exports?

Op di 27 dec. 2016 16:50 schreef Ryan M. <notifications@github.com>:

**Comment by laggingreflex** [comment]
There are currently two packages on npm: [`mobx-preact-alt`](https://www.npmjs.com/package/mobx-preact-alt) and [`mobx-preact`](https://www.npmjs.com/package/mobx-preact). From the looks of it they seem same, and point to this same repo. What's the other package for? If they're the same perhaps the -alt one should be deprecated and a redirect notice added on npm page for it?

**Comment by nightwolfz** [comment]
I will update this package soon 👍
